#!/usr/bin/env bash
set -euo pipefail

SWAY_DIR="$(dirname "$(dirname "$(realpath "$0")")")"
LIST_FILE="$SWAY_DIR/tiled_apps.list"
CONF_FILE="$SWAY_DIR/tiled.conf"

cat << 'EOF' > "$CONF_FILE"
# Auto-generated by scripts/generate-tiled-rules.sh
# Ref: ~/.config/sway/tiled_apps.list

# ALL new windows open as floating
for_window [app_id=".*"] floating enable
for_window [class=".*"] floating enable

# Dialog windows and popups always floating
for_window [window_type="dialog"] floating enable
for_window [window_role="dialog"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable

# Excludes (this one will be tiled)
EOF

if [[ -f "$LIST_FILE" ]]; then
    while IFS= read -r app || [[ -n "$app" ]]; do
        # remove whitespace chars from start and end
        app="$(echo "$app" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
        # skip empty lines and comments
        [[ -z "$app" || "$app" =~ ^# ]] && continue

        cat << EOF >> "$CONF_FILE"
for_window [app_id="(?i)$app"] floating disable
for_window [class="(?i)$app"] floating disable
EOF
    done < "$LIST_FILE"
fi
