#!/usr/bin/env bash
set -euo pipefail

SWAY_DIR="$(dirname "$(dirname "$(realpath "$0")")")"
LIST_FILE="$SWAY_DIR/tiled_apps.list"
CONF_FILE="$SWAY_DIR/tiled.conf"

# apps of the list, joined into one regex alternative
apps=()
if [[ -f "$LIST_FILE" ]]; then
    while IFS= read -r app || [[ -n "$app" ]]; do
        # remove whitespace chars from start and end
        app="$(echo "$app" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
        # skip empty lines and comments
        [[ -z "$app" || "$app" =~ ^# ]] && continue
        apps+=("$app")
    done <"$LIST_FILE"
fi
tiled=$(
    IFS='|'
    echo "${apps[*]}"
)
# with no tiled apps, an alternative matching nothing: every window floats
[[ -n "$tiled" ]] || tiled='$^'

# Tiled apps match no floating rule at all: sway runs every for_window rule
# anew on the first title change after a reload, and a window floated
# and tiled again comes back in another place of the layout.
cat <<EOF >"$CONF_FILE"
# Auto-generated by scripts/generate-tiled-rules.sh
# Ref: ~/.config/sway/tiled_apps.list

# ALL new windows open as floating, except the tiled ones
for_window [shell="xdg_shell" app_id="^(?!.*(?i:$tiled))"] floating enable
for_window [shell="xwayland" class="^(?!.*(?i:$tiled))"] floating enable

# Dialog windows and popups always floating
for_window [window_type="dialog"] floating enable
for_window [window_role="dialog"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable
EOF
