# PREFIX 
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# BASE
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"
set -g mouse on

# PLUGINS 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'thekylehuang/cole-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

# TPM 
run '~/.tmux/plugins/tpm/tpm'

# VIM BINDS
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3

# THEME OVERRIDES
set -g status-position bottom
set -g status-right-length 100
set -g status-right "#[fg=colour235,bg=colour108,bold] %H:%M #[fg=colour235,bg=colour179,bold] %d/%m/%Y "
