"$schema" = 'https://starship.rs/config-schema.json'
format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[ ](fg:color_yellow)\
$line_break$character"""

palette = 'custom'

[palettes.custom]
color_fg0    = "#ffffff"
color_bg1    = "#3d3d3d"
color_bg3    = "#101010"
color_blue   = "#6179c2"
color_aqua   = "#33919c"
color_green  = "#2e9969"
color_orange = "#cc5d4b"
color_purple = "#ab78ab"
color_red    = "#cc5d4b"
color_yellow = "#cc9b52"

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Fedora = "󰣛"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
