-- return {
--   -- {
--   --   'CustomCalculator',
--   --   name = 'custom-calc',
--   --   dir = vim.fn.stdpath 'config',
--   --   config = function()
--   --     vim.api.nvim_create_user_command(
--   --       'Calc',
--   --       function()
--   --         require('snacks').terminal.toggle('bc -l', {
--   --           win = {
--   --             position = 'float',
--   --             border = 'rounded',
--   --             title = ' Kalkulator ',
--   --             title_pos = 'center',
--   --           },
--   --         })
--   --       end,
--   --       { desc = 'Toggle Scientific Calculator' }
--   --     )
--   --
--   --     local function calculate_visual(action)
--   --       vim.cmd 'noau normal! "vy"'
--   --       local expr = vim.fn.getreg 'v'
--   --
--   --       local clean_expr = expr:gsub('\n', ''):gsub('=', ''):gsub('^%s*(.-)%s*$', '%1')
--   --
--   --       local cmd = string.format("echo 'scale=4; %s' | bc -l", clean_expr)
--   --       local result = vim.fn.system(cmd):gsub('\n', '')
--   --
--   --       if vim.v.shell_error ~= 0 or result:match 'syntax error' then
--   --         vim.notify('Błąd obliczeń dla: ' .. clean_expr, vim.log.levels.ERROR)
--   --         return
--   --       end
--   --
--   --       if result:match '%.' then result = result:gsub('0+$', ''):gsub('%.$', '') end
--   --       if result:sub(1, 1) == '.' then result = '0' .. result end
--   --
--   --       local new_text = ''
--   --       if action == 'replace' then
--   --         new_text = result
--   --       elseif action == 'append' then
--   --         new_text = clean_expr .. ' = ' .. result .. ' '
--   --       end
--   --
--   --       vim.fn.setreg('v', new_text)
--   --       vim.cmd 'normal! gv"vp'
--   --     end
--   --
--   --     vim.keymap.set('n', '<leader>tc', '<cmd>Calc<CR>', { desc = 'Toggle Calculator' })
--   --     vim.keymap.set('v', '<leader>cr', function() calculate_visual 'replace' end, { desc = 'Calc & Replace' })
--   --     vim.keymap.set('v', '<leader>ca', function() calculate_visual 'append' end, { desc = 'Calc & Append' })
--   --   end,
--   -- },
-- }
