-- return {
--   'lervag/vimtex',
--   lazy = false,
--   init = function()
--     vim.g.vimtex_view_method = 'zathura_simple'
--     vim.g.vimtex_view_general_viewer = 'zathura'
--     vim.g.vimtex_view_automatic = 0
--     vim.g.vimtex_quickfix_mode = 0
--     vim.g.vimtex_quickfix_open_on_warning = 0
--
--     local augroup = vim.api.nvim_create_augroup('vimtex_auto_compile', { clear = true })
--     vim.api.nvim_create_autocmd('BufWritePost', {
--       group = augroup,
--       pattern = '*.tex',
--       callback = function()
--         local is_running = false
--         local ok, val = pcall(function() return vim.fn.eval "exists('b:vimtex') && has_key(b:vimtex, 'compiler') && b:vimtex.compiler.is_running()" end)
--         if ok and val == 1 then is_running = true end
--         if not is_running then vim.cmd 'silent! VimtexCompile' end
--       end,
--     })
--
--     vim.api.nvim_create_autocmd('User', {
--       group = augroup,
--       pattern = 'VimtexEventCompileSuccess',
--       callback = function() vim.cmd 'silent! VimtexView' end,
--     })
--   end,
-- }
