-- return {
--   'folke/zen-mode.nvim',
--   cmd = 'ZenMode',
--   keys = {
--     { '<leader>z', function() require('zen-mode').toggle() end, desc = 'Toggle Zen Mode' },
--   },
--   opts = {
--     window = {
--       backdrop = 1,
--       width = 0.8,
--       height = 1,
--       options = {
--         signcolumn = 'no',
--         number = true,
--         relativenumber = false,
--         cursorline = true,
--         foldcolumn = '0',
--       },
--     },
--     plugins = {
--       options = {
--         enabled = true,
--         ruler = false,
--         showcmd = false,
--         laststatus = 0,
--       },
--       twilight = { enabled = false },
--       gitsigns = { enabled = true },
--       tmux = { enabled = true },
--     },
--   },
-- }
