background = #fff5ea
foreground = #584141
selection-background = #c9c0b8
selection-foreground = #fff5ea
selection-invert-fg-bg = true
palette = 0=#fff5ea
palette = 1=#ba2d2f
palette = 2=#007a0a
palette = 3=#a45a22
palette = 4=#375cc6
palette = 5=#ca3e54
palette = 6=#3f60af
palette = 7=#584141
palette = 8=#63728f
palette = 9=#cf2f4f
palette = 10=#0f7f5f
palette = 11=#b75515
palette = 12=#265fbf
palette = 13=#8448aa
palette = 14=#0f7b8f
palette = 15=#8f5f4a
