customCommands:
  - key: 'W'
    context: 'commits'
    description: 'Dodaj współautora i edytuj'
    prompts:
      - type: 'menuFromCommand'
        title: 'Wybierz współautora'
        key: 'Author'
        command: "bash -c \"(git log --format='%aN <%aE>'; git log --all --format='%(trailers:key=Co-authored-by,valueonly=true)') | sed '/^$/d' | sort -u\""
    command: >
      bash -c '
      COMMIT="{{.SelectedLocalCommit.Hash}}";
      BRANCH=$(git branch --show-current);
      if [ "$COMMIT" = "$(git rev-parse HEAD)" ]; then
        git commit --amend --no-edit --trailer "Co-authored-by: {{.Form.Author}}";
      else
        git checkout "$COMMIT" &&
        git commit --amend --no-edit --trailer "Co-authored-by: {{.Form.Author}}" &&
        git rebase --onto HEAD "$COMMIT" "$BRANCH";
      fi'

  - key: 'F'
    context: 'commits'
    description: 'Podpisz commit (własny)'
    command: >
      bash -c '
      COMMIT="{{.SelectedLocalCommit.Hash}}";
      BRANCH=$(git branch --show-current);
      if [ "$COMMIT" = "$(git rev-parse HEAD)" ]; then
        git commit --amend --no-edit --signoff;
      else
        git checkout "$COMMIT" &&
        git commit --amend --no-edit --signoff &&
        git rebase --onto HEAD "$COMMIT" "$BRANCH";
      fi'
