--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/wolfie/Pulpit/Osobiste/Tapety/hollow-knight.jpg"

-- Special
background="#0f1018"
foreground="#d0dae9"
cursor="#d0dae9"

-- Colors
color0="#0f1018"
color1="#606B86"
color2="#70758B"
color3="#837D84"
color4="#7C849D"
color5="#8792B0"
color6="#9CB0DA"
color7="#d0dae9"
color8="#9198a3"
color9="#606B86"
color10="#70758B"
color11="#837D84"
color12="#7C849D"
color13="#8792B0"
color14="#9CB0DA"
color15="#d0dae9"
