# Shell variables
# Generated by 'wal'
wallpaper='/home/wolfie/Pulpit/Osobiste/Tapety/hollow-knight.jpg'

# Special
background='#0f1018'
foreground='#d0dae9'
cursor='#d0dae9'

# Colors
color0='#0f1018'
color1='#606B86'
color2='#70758B'
color3='#837D84'
color4='#7C849D'
color5='#8792B0'
color6='#9CB0DA'
color7='#d0dae9'
color8='#9198a3'
color9='#606B86'
color10='#70758B'
color11='#837D84'
color12='#7C849D'
color13='#8792B0'
color14='#9CB0DA'
color15='#d0dae9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
