---
dnf_libs_packages:
  - ImageMagick-devel
  - R-srpm-macros
  - SDL2_ttf-devel
  - Xaw3d-devel
  - aalib-libs
  - accountsservice-libs
  - alsa-lib-devel
  - atk-devel
  - boost
  - boost-charconv
  - boost-cobalt
  - boost-container
  - boost-context
  - boost-contract
  - boost-coroutine
  - boost-fiber
  - boost-graph
  - boost-json
  - boost-log
  - boost-math
  - boost-nowide
  - boost-numpy3
  - boost-process
  - boost-python3
  - boost-random
  - boost-serialization
  - boost-stacktrace
  - boost-test
  - boost-timer
  - boost-type_erasure
  - boost-url
  - boost-wave
  - clang-devel
  - cmake-srpm-macros
  - dbus-devel
  - emacs-filesystem
  - ffmpeg-devel
  - ffmpeg-libs
  - fontconfig-devel
  - giflib-devel
  - gimp-libs
  - gnutls-devel
  - gpm-devel
  - gpm-libs
  - gtk3-devel
  - gtk4-devel
  - java-25-openjdk-devel
  - libX11-devel
  - libXcursor-devel
  - libXdmcp-devel
  - libXi-devel
  - libXpm-devel
  - libXrandr-devel
  - libXt-devel
  - libacl-devel
  - libadwaita-devel
  - libarrow-compute-libs
  - libbpf-devel
  - libcxx-devel
  - libgccjit-devel
  - libjpeg-turbo-devel
  - libnghttp3-devel
  - libotf-devel
  - librsvg2-devel
  - libtiff-devel
  - libtree-sitter-devel
  - libvterm-devel
  - libwebp-devel
  - m17n-lib-devel
  - mesa-libGL-devel
  - ncurses-devel
  - ngtcp2-crypto-ossl-devel
  - ngtcp2-devel
  - nodejs22-libs
  - notmuch-devel
  - openapv-libs
  - qemu-user-static
  - rust-std-static
  - samba-core-libs
  - samba-ndr-libs
  - sdl2-compat-devel
  - selinux-policy-devel
  - sqlite-devel
  - systemd-devel
  - tpm2-tss-devel
  - webkit2gtk4.1-devel
