---
dnf_latex_packages:
  - emacs-auctex
  - texlive-acro
  - texlive-addtoluatexpath
  - texlive-advice
  - texlive-aiplans
  - texlive-aliascnt
  - texlive-amslatex-primer
  - texlive-amsldoc-it
  - texlive-amsmath-it
  - texlive-amsthdoc-it
  - texlive-answers
  - texlive-antique-spanish-units
  - texlive-apprends-latex
  - texlive-around-the-bend
  - texlive-arrayjobx
  - texlive-ascii-chart
  - texlive-ascmac
  - texlive-aspen
  - texlive-asy-overview
  - texlive-atableau
  - texlive-autotype
  - texlive-bbm-macros
  - texlive-beamer-tut-pt
  - texlive-biblatex-accursius
  - texlive-biblatex-cheatsheet
  - texlive-biblatex-ext
  - texlive-booktabs-de
  - texlive-booktabs-fr
  - texlive-bracealign
  - texlive-breakcites
  - texlive-broydensolve
  - texlive-bussproofs-colorful
  - texlive-cahierprof
  - texlive-calcfrac
  - texlive-char2path
  - texlive-chemfig
  - texlive-chemformula-ru
  - texlive-chicago
  - texlive-circuitikz
  - texlive-citeref
  - texlive-cleveref
  - texlive-cmexb
  - texlive-collargs
  - texlive-collcell
  - texlive-coloredtheorem
  - texlive-complexpolylongdiv
  - texlive-components
  - texlive-comprehensive
  - texlive-context-calendar-examples
  - texlive-context-chat
  - texlive-context-collating-marks
  - texlive-context-legacy
  - texlive-context-notes-zh-cn
  - texlive-context-pocketdiary
  - texlive-context-squares
  - texlive-context-sudoku
  - texlive-contour
  - texlive-cora-macs
  - texlive-couleurs-fr
  - texlive-cs-techrep
  - texlive-csquotes-de
  - texlive-cstex
  - texlive-csthm
  - texlive-ctan_chk
  - texlive-cursolatex
  - texlive-dantelogo
  - texlive-decimalcomma
  - texlive-diagbox
  - texlive-dickimaw
  - texlive-dingbat
  - texlive-docsurvey
  - texlive-domaincoloring
  - texlive-dtk-bibliography
  - texlive-dtxdescribe
  - texlive-dtxtut
  - texlive-dvipng
  - texlive-dvisvgm
  - texlive-dynkin-diagrams
  - texlive-easydtx
  - texlive-elocalloc
  - texlive-eoldef
  - texlive-epslatex-fr
  - texlive-eqnlines
  - texlive-es-tex-faq
  - texlive-etdipa
  - texlive-etoolbox-de
  - texlive-etoolbox-generic
  - texlive-euclidean-lattice
  - texlive-everyhook
  - texlive-expex
  - texlive-expltools
  - texlive-extractbb
  - texlive-fancyhdr-it
  - texlive-fancymag
  - texlive-faq-fr
  - texlive-faq-fr-gutenberg
  - texlive-farbe
  - texlive-fetamont
  - texlive-fifinddo-info
  - texlive-first-latex-doc
  - texlive-fitch
  - texlive-fnpara
  - texlive-fodot
  - texlive-footnotebackref
  - texlive-forarray
  - texlive-forest
  - texlive-forest-quickstart
  - texlive-fragoli
  - texlive-freealign
  - texlive-freemath
  - texlive-fundus-calligra
  - texlive-gitinfo-lua
  - texlive-guide-to-latex
  - texlive-happy4th
  - texlive-hep-graphic
  - texlive-hideproofs
  - texlive-hook-pre-commit-pkg
  - texlive-huffman
  - texlive-hypcap
  - texlive-hyphen-albanian
  - texlive-ideavault
  - texlive-ifis-macros
  - texlive-impatient
  - texlive-impatient-fr
  - texlive-inconsolata
  - texlive-inlinedef
  - texlive-intexgral
  - texlive-intro-scientific
  - texlive-isphysicalmath
  - texlive-keyfloat
  - texlive-keyparse
  - texlive-keytheorems
  - texlive-kkluaverb
  - texlive-kkran
  - texlive-kksymbols
  - texlive-knowledge
  - texlive-koma-script-examples
  - texlive-l2picfaq
  - texlive-l2tabu-english
  - texlive-l2tabu-french
  - texlive-l2tabu-spanish
  - texlive-l3sys-query
  - texlive-lambdax
  - texlive-latex-brochure
  - texlive-latex-course
  - texlive-latex-doc-ptr
  - texlive-latex-graphics-companion
  - texlive-latex-refsheet
  - texlive-latex-veryshortguide
  - texlive-latex-web-companion
  - texlive-latex2e-help-texinfo-fr
  - texlive-latex4wp
  - texlive-latex4wp-it
  - texlive-latexcheat
  - texlive-latexcheat-de
  - texlive-latexcheat-esmx
  - texlive-latexcheat-ptbr
  - texlive-latexcourse-rug
  - texlive-lcd
  - texlive-linearregression
  - texlive-linegoal
  - texlive-linkedthm
  - texlive-logictools
  - texlive-longmath
  - texlive-lshort-czech
  - texlive-lshort-dutch
  - texlive-lshort-english
  - texlive-lshort-estonian
  - texlive-lshort-finnish
  - texlive-lshort-french
  - texlive-lshort-italian
  - texlive-lshort-polish
  - texlive-lshort-portuguese
  - texlive-lshort-slovak
  - texlive-lshort-slovenian
  - texlive-lshort-spanish
  - texlive-lshort-turkish
  - texlive-ltx-talk
  - texlive-lua-placeholders
  - texlive-lua-regression
  - texlive-lua-tinyyaml
  - texlive-lua-unicode-math
  - texlive-luahttp
  - texlive-luakeyval
  - texlive-lualatex-doc-de
  - texlive-luamml
  - texlive-luanumint
  - texlive-luaplot
  - texlive-luatbls
  - texlive-luatex-type-definitions
  - texlive-luatexja
  - texlive-luatikz
  - texlive-ly1
  - texlive-macros2e
  - texlive-makecell
  - texlive-makerobust
  - texlive-marginalia
  - texlive-math-into-latex-4
  - texlive-math-operator
  - texlive-mathgreeks
  - texlive-maths-symbols
  - texlive-measurebox
  - texlive-media9
  - texlive-medmath
  - texlive-memdesign
  - texlive-memoirchapterstyles
  - texlive-metafont-beginners
  - texlive-metapost-examples
  - texlive-microtype-de
  - texlive-minifp
  - texlive-mlawriter
  - texlive-mleftright
  - texlive-moremath
  - texlive-mp-geom2d
  - texlive-mp-neuralnetwork
  - texlive-mpchess
  - texlive-mpkiviat
  - texlive-ninecolors
  - texlive-numbersets
  - texlive-ocg-p
  - texlive-ocgx
  - texlive-ocgx2
  - texlive-odesandpdes
  - texlive-old-arrows
  - texlive-padcount
  - texlive-panneauxroute
  - texlive-paracol
  - texlive-parnotes
  - texlive-parstat
  - texlive-patgen2-tutorial
  - texlive-pdfrender
  - texlive-pdftoolbox
  - texlive-penlightplus
  - texlive-perltex
  - texlive-physics-patch
  - texlive-physics3
  - texlive-pictexsum
  - texlive-plain-doc
  - texlive-plain-widow
  - texlive-pmdraw
  - texlive-ppmcheckpdf
  - texlive-preprint
  - texlive-profsio
  - texlive-psfrag-italian
  - texlive-pst-calculate
  - texlive-pst-pdf
  - texlive-ptlatexcommands
  - texlive-quantikz
  - texlive-quantum-chemistry-bonn
  - texlive-quantumcubemodel
  - texlive-quickreaction
  - texlive-quiver
  - texlive-quran
  - texlive-quran-en
  - texlive-quran-es
  - texlive-qworld
  - texlive-reptheorem
  - texlive-rigidnotation
  - texlive-runtexfile
  - texlive-runtexshebang
  - texlive-scalerel
  - texlive-scheme-basic
  - texlive-scheme-medium
  - texlive-seatingchart
  - texlive-semesterplannerlua
  - texlive-shadethm
  - texlive-shadowtext
  - texlive-show-pdf-tags
  - texlive-simplified-latex
  - texlive-sourcecodepro
  - texlive-sqltex
  - texlive-stretchy
  - texlive-string-diagrams
  - texlive-stringstrings
  - texlive-sttools
  - texlive-svg-inkscape
  - texlive-sympycalc
  - texlive-tabu
  - texlive-tabularray
  - texlive-tabularray-abnt
  - texlive-tagging
  - texlive-tagpdf
  - texlive-tamethebeast
  - texlive-tango
  - texlive-tds
  - texlive-templates-fenn
  - texlive-templates-sommer
  - texlive-temporal-logic
  - texlive-tensormatrix
  - texlive-termcal
  - texlive-tex-font-errors-cheatsheet
  - texlive-tex-overview
  - texlive-tex-virtual-academy-pl
  - texlive-texblend
  - texlive-texbytopic
  - texlive-texfindpkg
  - texlive-texlive-common
  - texlive-texlive-cz
  - texlive-texlive-de
  - texlive-texlive-es
  - texlive-texlive-fr
  - texlive-texlive-it
  - texlive-texlive-pl
  - texlive-textpos
  - texlive-thmtools
  - texlive-tikz-feynman
  - texlive-tikzscale
  - texlive-tipa-de
  - texlive-titlepages
  - texlive-tkz-interval
  - texlive-tlc2
  - texlive-tokcycle
  - texlive-tokmap
  - texlive-totcount
  - texlive-translation-array-fr
  - texlive-translation-arsclassica-de
  - texlive-translation-biblatex-de
  - texlive-translation-chemsym-de
  - texlive-translation-dcolumn-fr
  - texlive-translation-ecv-de
  - texlive-translation-enumitem-de
  - texlive-translation-europecv-de
  - texlive-translation-filecontents-de
  - texlive-translation-moreverb-de
  - texlive-translation-natbib-fr
  - texlive-translation-tabbing-fr
  - texlive-trivfloat
  - texlive-truncate
  - texlive-tuple
  - texlive-typstfun
  - texlive-undergradmath
  - texlive-unibidi-lua
  - texlive-uri
  - texlive-verse
  - texlive-visualfaq
  - texlive-visualtikz
  - texlive-visualtoks
  - texlive-voss-mathcol
  - texlive-webguide
  - texlive-wrapstuff-doc-en
  - texlive-xcomment
  - texlive-xdvipsk
  - texlive-xdvipsk-support
  - texlive-xetexref
  - texlive-xfrac
  - texlive-xii
  - texlive-xindy
  - texlive-xsavebox
  - texlive-xurl
  - texlive-xypic-tut-pt
  - texlive-zeckendorf
