---
dnf_common_packages:
  - NetworkManager-tui
  - aalib
  - ansible
  - antigravity
  - babl
  - bat
  - bluez-deprecated
  - busybox
  - cava
  - chafa
  - cockpit-networkmanager
  - default-fonts-ii
  - dnf-plugins-core
  - dnf5
  - dns-root-data
  - execstack
  - fastfetch
  - fcgi
  - fedora-repos-rawhide
  - ffcall
  - filesystem
  - fontawesome4-fonts
  - fuse
  - gegl04
  - gegl04-matting-levin
  - gh
  - ghostty
  - git-core
  - git-delta
  - git-email
  - git-lfs
  - gjs
  - glfw
  - gmime30
  - gnupg2-g13
  - gnupg2-utils
  - gnupg2-wks
  - go-l2tp
  - google-noto-sans-yi-fonts
  - grub2-efi-ia32-modules
  - grub2-efi-x64-modules
  - grubby
  - gtk2
  - gtk2-engines
  - guile30
  - harfbuzz-gpu
  - harfbuzz-raster
  - harfbuzz-vector
  - hipblas
  - hunspell-en-AU
  - hunspell-en-CA
  - ibus-gtk2
  - inxi
  - isomd5sum
  - jetbrains-mono-fonts-all
  - knighttime
  - lazygit
  - libappstream-glib
  - libasan
  - libcanberra-gtk2
  - libdnf5-plugin-appstream
  - libdnf5-plugin-expired-pgp-keys
  - liberation-fonts-all
  - libgexiv2_0.14
  - libgit2
  - libglade2
  - libmypaint
  - libnghttp3
  - libnma-common
  - libnsgif
  - libpfm
  - libpmemobj
  - libportal
  - libportal-gtk3
  - libquadmath
  - libreoffice-ure-common
  - libsvm
  - libtsan
  - libubsan
  - libultrahdr
  - libva-utils
  - libwmf
  - libxcrypt-compat
  - linkdupes
  - llhttp
  - lsd
  - md4c
  - micro
  - mozjs140
  - mypaint-brushes
  - nfs-client-utils
  - nfs-common-utils
  - nfsv3-client-utils
  - nfsv4-client-utils
  - ngtcp2-crypto-gnutls
  - ngtcp2-crypto-ossl
  - openblas-openmp
  - optipng
  - pandoc-cli
  - perl-Image-ExifTool
  - perl-String-ShellQuote
  - picocom
  - powertop
  - rdma-core-common
  - sassc
  - screen
  - steam-arch-transition
  - stow
  - systemd-oomd-defaults
  - tmux
  - tokei
  - ttfautohint
  - udev-hid-bpf
  - udev-hid-bpf-stable
  - udisks2-btrfs
  - vim-enhanced
  - w3m
  - wcurl
  - x11vnc
  - xapian-core
  - xdotool
  - xxd
  - yazi
  - yyjson
  - zsh
