---
dnf_dev_packages:
  - alloyctl
  - arm-none-eabi-gcc-cs
  - arm-none-eabi-gcc-cs-c++
  - arm-none-eabi-newlib
  - bear
  - binutils-sparc64-linux-gnu
  - bison
  - capstone
  - cargo
  - carmenta
  - clang
  - clang-analyzer
  - clang-tools-extra
  - clisp
  - cmake
  - coccinelle
  - copr-cli
  - createrepo_c
  - debootstrap
  - dwarves
  - emacs-pgtk
  - flex
  - flexiblas
  - flexiblas-netlib
  - flexiblas-openblas-openmp
  - flexiblas-openblas-serial
  - gcc-sparc64-linux-gnu
  - gdb
  - golang
  - helm
  - iwyu
  - java-25-openjdk-crypto-adapter
  - john
  - libtool
  - lld
  - llvm
  - lua-lgi-compat
  - luarocks
  - mingw64-gcc
  - nasm
  - neovim
  - ninja-build
  - nodejs22
  - nodejs22-bin
  - nodejs22-docs
  - nodejs22-full-i18n
  - nodejs22-npm
  - nodejs22-npm-bin
  - pari
  - php
  - podman-sequoia
  - python3-bugzilla
  - python3-dnf-plugins-core
  - python3-ibus
  - python3-markdown-it-py
  - python3-mdurl
  - python3-pip
  - python3-rich
  - python3-rich-click
  - python3-sphinx
  - python3-tkinter
  - python3.12
  - rpm-build
  - rpm-sign
  - rpmlint
  - ruff
  - rust
  - sparse
  - strace
  - suitesparse
  - tailscale
  - valgrind
  - veristat
