(let ((modules-dir (expand-file-name "modules" user-emacs-directory)))
  (add-to-list 'load-path modules-dir)
  (let ((default-directory modules-dir))
    (normal-top-level-add-subdirs-to-load-path)))

(require 'core)
(require 'evil-mod)
(require 'ui-mod)
(require 'completion-mod)
(require 'lsp-mod)
(require 'treemacs-mod)
(require 'projectile-mod)
(require 'git-mod)
(require 'terminal-mod)
(require 'dashboard-mod)
(require 'tabs-mod)
(require 'latex-mod)

(provide 'init)
