[colors]
background = '#1214148e'
black = '#121414'
blue = '#9fb0b1'
cursor = '#e3e2e2'
cyan = '#c7c7dc'
foreground = '#d5dede'
green = '#8ae2f8'
magenta = '#bedbdc'
red = '#8af5fa'
tabs = '#d5dede'
tabs-active = '#93fcd5'
white = '#d5dede'
yellow = '#bafd89'
dim-black = '#1214148e'
dim-blue = '#9fb0b18e'
dim-cyan = '#c7c7dc8e'
dim-foreground = '#d5dede8e'
dim-green = '#8ae2f88e'
dim-magenta = '#bedbdc8e'
dim-red = '#8af5fa8e'
dim-white = '#93fcd58e'
dim-yellow = '#bafd898e'
light-black = '#abbabb'
light-blue = '#cecee0'
light-cyan = '#9ce5f9'
light-foreground = '#c7dfe0'
light-green = '#9df6fa'
light-magenta = '#a4fcda'
light-red = '#c3fe9b'
light-white = '#abbabb'
light-yellow = '#cecee0'
