[colors.primary]
background = "#121414"
foreground = "#d5dede"

[colors.cursor]
text = "#121414"
cursor = "#d5dede"

[colors.vi_mode_cursor]
text = "#121414"
cursor = "#d5dede"

[colors.search.matches]
foreground = "#121414"
background = "#c3fe9b"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#acb4b4"
background = "#bafd89"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#121414"
red = "#9fb0b1"
green = "#c7c7dc"
yellow = "#8ae2f8"
blue = "#bedbdc"
magenta = "#8af5fa"
cyan = "#93fcd5"
white = "#bafd89"

[colors.bright]
black = "#acb4b4"
red = "#abbabb"
green = "#cecee0"
yellow = "#9ce5f9"
blue = "#c7dfe0"
magenta = "#9df6fa"
cyan = "#a4fcda"
white = "#c3fe9b"

[colors.dim]
black = "#c3fe9b"
red = "#abbabb"
green = "#9df6fa"
yellow = "#9ce5f9"
blue = "#c7dfe0"
magenta = "#cecee0"
cyan = "#a4fcda"
white = "#acb4b4"

