--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/wolfie/Pulpit/Osobiste/Tapety/wallhaven-9d331d.png"

-- Special
background="#01021C"
foreground="#f4a09e"
cursor="#f4a09e"

-- Colors
color0="#01021C"
color1="#304658"
color2="#5E5358"
color3="#B0093F"
color4="#F60B4B"
color5="#F42A4A"
color6="#A05E55"
color7="#f4a09e"
color8="#aa706e"
color9="#304658"
color10="#5E5358"
color11="#B0093F"
color12="#F60B4B"
color13="#F42A4A"
color14="#A05E55"
color15="#f4a09e"
