# Shell variables
# Generated by 'wal'
wallpaper="/home/wolfie/Pulpit/Osobiste/Tapety/pawel-czerwinski-mQ9ITEx3L-c-unsplash.jpg"

# Special
background='#121414'
foreground='#d5dede'
cursor='#e3e2e2'

# Colors
color0='#121414'
color1='#9fb0b1'
color2='#c7c7dc'
color3='#8ae2f8'
color4='#bedbdc'
color5='#8af5fa'
color6='#93fcd5'
color7='#bafd89'
color8='#acb4b4'
color9='#abbabb'
color10='#cecee0'
color11='#9ce5f9'
color12='#c7dfe0'
color13='#9df6fa'
color14='#a4fcda'
color15='#c3fe9b'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
