# PREFIX 
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# BASE
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"
set -g mouse on
set -g allow-passthrough on
set -g base-index 1
setw -g pane-base-index 1

# PLUGINS 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'thekylehuang/cole-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'p'

set -g @plugin 'omerxx/tmux-floax'
set -g @floax-bind '-n M-f'
set -g @floax-bind-menu 'M-m'
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'colour108'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# TMUX-JOT
set -g @sessionx-filter-mattes '.*tmux_jot.*'
set -g @jot-border-color '#b38d59'
set -g @jot-border-style 'rounded'
set -g @jot-popup-x 'R'
set -g @jot-popup-y '0'
set -g @jot-popup-width '40%'
set -g @jot-popup-height '50%'
set -g @jot-editor "nvim"
set -g @plugin 'szymonwilczek/tmux-jot'

# TPM
run '~/.tmux/plugins/tpm/tpm'

# PANES
bind -n M-n split-window -h -c "#{pane_current_path}"
bind h select-pane -L
bind l select-pane -R

## RESIZE PANES
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind e select-layout even-horizontal

# TABS
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5

# THEME OVERRIDES
set -g status-position bottom
set -g status-right-length 100
set -g status-right "#[fg=colour235,bg=colour108,bold] %H:%M #[fg=colour235,bg=colour179,bold] %d/%m/%Y "
