# Vim-like marks for windows
# $mod+m <letter> marks the focused window,
# $mod+' <letter> focuses the window with that mark,
# switching to its workspace and output.
# Marks are added, so marks set by scripts stay in place.

bindsym $mod+m mode "mark"
mode "mark" {
    bindsym a mark --add a; mode "default"
    bindsym b mark --add b; mode "default"
    bindsym c mark --add c; mode "default"
    bindsym d mark --add d; mode "default"
    bindsym e mark --add e; mode "default"
    bindsym f mark --add f; mode "default"
    bindsym g mark --add g; mode "default"
    bindsym h mark --add h; mode "default"
    bindsym i mark --add i; mode "default"
    bindsym j mark --add j; mode "default"
    bindsym k mark --add k; mode "default"
    bindsym l mark --add l; mode "default"
    bindsym m mark --add m; mode "default"
    bindsym n mark --add n; mode "default"
    bindsym o mark --add o; mode "default"
    bindsym p mark --add p; mode "default"
    bindsym q mark --add q; mode "default"
    bindsym r mark --add r; mode "default"
    bindsym s mark --add s; mode "default"
    bindsym t mark --add t; mode "default"
    bindsym u mark --add u; mode "default"
    bindsym v mark --add v; mode "default"
    bindsym w mark --add w; mode "default"
    bindsym x mark --add x; mode "default"
    bindsym y mark --add y; mode "default"
    bindsym z mark --add z; mode "default"
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+apostrophe mode "goto"
mode "goto" {
    bindsym a [con_mark="^a$"] focus; mode "default"
    bindsym b [con_mark="^b$"] focus; mode "default"
    bindsym c [con_mark="^c$"] focus; mode "default"
    bindsym d [con_mark="^d$"] focus; mode "default"
    bindsym e [con_mark="^e$"] focus; mode "default"
    bindsym f [con_mark="^f$"] focus; mode "default"
    bindsym g [con_mark="^g$"] focus; mode "default"
    bindsym h [con_mark="^h$"] focus; mode "default"
    bindsym i [con_mark="^i$"] focus; mode "default"
    bindsym j [con_mark="^j$"] focus; mode "default"
    bindsym k [con_mark="^k$"] focus; mode "default"
    bindsym l [con_mark="^l$"] focus; mode "default"
    bindsym m [con_mark="^m$"] focus; mode "default"
    bindsym n [con_mark="^n$"] focus; mode "default"
    bindsym o [con_mark="^o$"] focus; mode "default"
    bindsym p [con_mark="^p$"] focus; mode "default"
    bindsym q [con_mark="^q$"] focus; mode "default"
    bindsym r [con_mark="^r$"] focus; mode "default"
    bindsym s [con_mark="^s$"] focus; mode "default"
    bindsym t [con_mark="^t$"] focus; mode "default"
    bindsym u [con_mark="^u$"] focus; mode "default"
    bindsym v [con_mark="^v$"] focus; mode "default"
    bindsym w [con_mark="^w$"] focus; mode "default"
    bindsym x [con_mark="^x$"] focus; mode "default"
    bindsym y [con_mark="^y$"] focus; mode "default"
    bindsym z [con_mark="^z$"] focus; mode "default"
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
